language: go
go:
  - 1.3
  - 1.5
  - 1.7
  - 1.8
  - tip
script:
  - go test -coverprofile=coverage.txt -covermode=atomic
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install
  - gometalinter --config=gometalinter.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
